/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

 import java.sql.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;


public class Mtransaksi extends javax.swing.JDialog {
      private String jdbcURL = "jdbc:oracle:thin:@//localhost:1521/xepdb1";//ssid
   //private String jdbcURL = "jdbc:oracle:thin:@//172.23.9.185:1521/orcl";//service
    private String user = "hr";
    private String password = "hr";
    private Connection connection = null;
    private Statement stmt=null;
    private ResultSet rs=null;
    isiPerpus dtPerpus;
    Peminjam dtpeminjam;
    Koleksi dtKoleksi;
    Transaksi dtTransaksi;
    ArrayList<Koleksi> dtPesanKoleksi;
    ArrayList<Transaksi> dtTrx = new ArrayList();
    DefaultTableModel tbModelPesanKoleksi;
    DefaultTableModel tbModelTransaksi;
    TableColumnModel clModelPesanKoleksi;
    TableColumnModel clModelTransaksi;

    /**
     * Creates new form dTransaksi
     */
    public Mtransaksi(java.awt.Frame parent, boolean modal, isiPerpus dtPerpus) {
        super(parent, modal);
        initComponents();
        this.dtPerpus = dtPerpus;
        dtPesanKoleksi = new ArrayList();
        tampilKoleksi();
        tampilTransaksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblNo1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txID = new javax.swing.JTextField();
        txNama = new javax.swing.JTextField();
        txJumPinjam = new javax.swing.JTextField();
        txNip = new javax.swing.JTextField();
        txAlamat = new javax.swing.JTextField();
        tCari = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txIDk = new javax.swing.JTextField();
        txJudul = new javax.swing.JTextField();
        txPenerbit = new javax.swing.JTextField();
        txStatus = new javax.swing.JTextField();
        txIssn = new javax.swing.JTextField();
        tCaruKoleksi = new javax.swing.JButton();
        lVolumeK = new javax.swing.JLabel();
        txVolume = new javax.swing.JTextField();
        lSeriK = new javax.swing.JLabel();
        txSeri = new javax.swing.JTextField();
        tTambahPesan = new javax.swing.JButton();
        tBatalK = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btPinjam = new javax.swing.JButton();
        tBatal = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        DataTransaksi = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        Simpan = new javax.swing.JButton();
        Buka = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        Detil = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelKoleksi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kelola Data Transaksi Peminjaman");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Peminjam"));

        jLabel2.setText("ID Peminjam");

        lblNo1.setText("Nama");

        jLabel6.setText("Alamat");

        jLabel7.setText("Jumlah Pinjam");

        jLabel8.setText("NIP");

        txID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txIDActionPerformed(evt);
            }
        });

        txNama.setEditable(false);

        txJumPinjam.setEditable(false);

        txNip.setEditable(false);

        txAlamat.setEditable(false);

        tCari.setText("Cari");
        tCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txID, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tCari, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(lblNo1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txJumPinjam, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txAlamat, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txNama)
                            .addComponent(txNip))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNo1)
                    .addComponent(txNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txJumPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txNip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Koleksi"));

        jLabel1.setText("ID Koleksi");

        lblNo.setText("Judul");

        jLabel3.setText("Penerbit");

        jLabel4.setText("Status");

        jLabel5.setText("ISBN/ISSN");

        txJudul.setEditable(false);

        txPenerbit.setEditable(false);

        txStatus.setEditable(false);

        txIssn.setEditable(false);

        tCaruKoleksi.setText("Cari");
        tCaruKoleksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCaruKoleksiActionPerformed(evt);
            }
        });

        lVolumeK.setText("Volume");

        txVolume.setEditable(false);

        lSeriK.setText("Seri");

        txSeri.setEditable(false);

        tTambahPesan.setText("Tambah Pesanan");
        tTambahPesan.setEnabled(false);
        tTambahPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTambahPesanActionPerformed(evt);
            }
        });

        tBatalK.setText("Batal Pesanan");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNo)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txIDk, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tCaruKoleksi, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                            .addComponent(txJudul)
                            .addComponent(txPenerbit)
                            .addComponent(txStatus)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lVolumeK)
                            .addComponent(lSeriK))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txIssn)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txSeri, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(txVolume))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tBatalK, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tTambahPesan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txIDk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tCaruKoleksi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNo)
                    .addComponent(txJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txIssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tBatalK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lVolumeK)
                            .addComponent(txVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lSeriK)
                            .addComponent(txSeri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tTambahPesan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Transaksi Peminjaman"));

        btPinjam.setText("Proses Peminjaman");
        btPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPinjamActionPerformed(evt);
            }
        });

        tBatal.setText("Batal");
        tBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btPinjam)
                .addComponent(tBatal))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Transaksi "));

        DataTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(DataTransaksi);

        Simpan.setText("Simpan");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });

        Buka.setText("Buka");
        Buka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BukaActionPerformed(evt);
            }
        });

        Hapus.setText("Hapus");

        Detil.setText("Detil");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Buka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Detil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(Detil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Buka, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 911, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Daftar Pesanan Koleksi"));

        TabelKoleksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabelKoleksi);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCariActionPerformed
        // TODO add your handling code here:
         if (cariPeminjam(txID.getText()) == null) {
           JOptionPane.showMessageDialog(this, "ID Peminjam tidak terdefinisi!!","Warning",JOptionPane.WARNING_MESSAGE); 
           return;
        }
        dtpeminjam = cariPeminjam(txID.getText());
        txNama.setText(dtpeminjam.getNama());
        txAlamat.setText(dtpeminjam.getAlamat());
        txJumPinjam.setText(Integer.toString(dtpeminjam.mak_pinjam));
        char tipe = dtpeminjam.getId().charAt(0);
        switch (tipe) {
            case 'D':
                txNip.setText(((Dosen)dtpeminjam).getNip());
                break;
            case 'M':
                txNip.setText(((Mahasiswa)dtpeminjam).getNim());
                break;
            case 'U':
                txNip.setText(((Umum)dtpeminjam).getNik());
                break;
            default:
                JOptionPane.showMessageDialog(this, "ID Peminjam tidak terdefinisi!!","Warning",JOptionPane.WARNING_MESSAGE);
                txNip.setText("No ID");
        }
      
    }//GEN-LAST:event_tCariActionPerformed

    private void tCaruKoleksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCaruKoleksiActionPerformed
        // TODO add your handling code here:
           if (cariKoleksi(txIDk.getText()) == null) {
           JOptionPane.showMessageDialog(this, "ID Koleksi tidak terdefinisi!!","Warning",JOptionPane.WARNING_MESSAGE); 
           return;
        }
        dtKoleksi = cariKoleksi(txIDk.getText());
        txJudul.setText(dtKoleksi.getJudul());
        txPenerbit.setText(dtKoleksi.getPenerbit());
        txStatus.setText(dtKoleksi.statuc_peminjam ? "Dipinjam":"Tersedia");
        tTambahPesan.setEnabled(!dtKoleksi.statuc_peminjam);
        char tipe = dtKoleksi.getId_Koleksi().charAt(0);
        switch (tipe) {
            case 'D':
                lVolumeK.setText("Format");
                lSeriK.setText("   ");
                txSeri.setVisible(Boolean.FALSE);
                txIssn.setText(((Disk)dtKoleksi).getIsbn());
                txVolume.setText(((Disk)dtKoleksi).getFormat());
                break;
            case 'M':
                lVolumeK.setText("Volume");
                lSeriK.setText("Seri");
                txSeri.setVisible(Boolean.TRUE);
                txIssn.setText(((majalah)dtKoleksi).getIssn());
                txVolume.setText(Integer.toString(((majalah)dtKoleksi).getVolume()));
                txSeri.setText(Integer.toString(((majalah)dtKoleksi).getSeri()));
                break;
            case 'B':
                lVolumeK.setText("Halaman");
                lSeriK.setText("   ");
                txSeri.setVisible(Boolean.FALSE);
                txIssn.setText(((Buku)dtKoleksi).getIsbn());
                txVolume.setText(Integer.toString(((Buku)dtKoleksi).getHalaman()));
                break;
            default:
                JOptionPane.showMessageDialog(this, "ID Koleksi tidak terdefinisi!!","Warning",JOptionPane.WARNING_MESSAGE);
                txNip.setText("No ID");
        }
        tTambahPesan.setEnabled(Boolean.TRUE);
    }//GEN-LAST:event_tCaruKoleksiActionPerformed

    private void tTambahPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTambahPesanActionPerformed
        // TODO add your handling code here:
        dtPesanKoleksi.add(dtKoleksi);
        tampilKoleksi();
        clrKoleksi();
    }//GEN-LAST:event_tTambahPesanActionPerformed

    private void btPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPinjamActionPerformed
        // TODO add your handling code here:
        LocalDateTime timeTrx = LocalDateTime.now();
        String idT = "T"+ Long.toString(timeTrx.toEpochSecond(ZoneOffset.UTC));
        dtTransaksi = new Transaksi();
        dtTransaksi.pinjam(idT, dtPesanKoleksi , dtpeminjam);
        dtTransaksi.pinjam(idT,dtPesanKoleksi,dtpeminjam);
        dtTrx.add(dtTransaksi);
        tampilTransaksi();
        clrKoleksi();
        clrPeminjam();
        dtPesanKoleksi.clear();
        tampilKoleksi();
    }//GEN-LAST:event_btPinjamActionPerformed

    private void tBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBatalActionPerformed
        // TODO add your handling code here:
        dtPesanKoleksi.clear();
        clrKoleksi();
        clrPeminjam();
        this.dispose();
        
    }//GEN-LAST:event_tBatalActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        FileOutputStream  outFileStream  = null;
        ObjectOutputStream outObjectStream = null;
        try {
            File     outFile  = new File("D:\\Informatika semester 3\\pbo Transaksi/transaksi.txt");
            outFileStream = new FileOutputStream(outFile);
            outObjectStream = new ObjectOutputStream(outFileStream);
            outObjectStream.writeObject(dtTrx);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Mtransaksi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Mtransaksi.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                outObjectStream.close();
                outFileStream.close();
            } catch (IOException ex) {
                Logger.getLogger(Mtransaksi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_SimpanActionPerformed

    private void BukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BukaActionPerformed
        FileInputStream   inFileStream  = null;
        ObjectInputStream inObjectStream  = null;
        try {
            File inFile  = new File("D:\\Informatika semester 3\\pbo Transaksi/transaksi.txt");
            inFileStream = new FileInputStream(inFile);
            inObjectStream  = new ObjectInputStream(inFileStream);
            try {
                dtTrx = (ArrayList<Transaksi>)inObjectStream.readObject();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Mtransaksi.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Mtransaksi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Mtransaksi.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                inObjectStream.close();
                inFileStream.close();
            } catch (IOException ex) {
                Logger.getLogger(Mtransaksi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        tampilTransaksi();
    }//GEN-LAST:event_BukaActionPerformed

    private void txIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mtransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mtransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mtransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mtransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

    }

    private Koleksi cariKoleksi(String idKoleksi) {
        Iterator<Koleksi> iterator = dtPerpus.koleksiList.iterator();
        while (iterator.hasNext()) {
            Koleksi koleksi = iterator.next();
            if (koleksi.getId_Koleksi().equals(idKoleksi)) {
                return koleksi;
            }
        }
        return null;
    }    
    private Peminjam cariPeminjam(String idPeminjam) {
        Iterator<Peminjam> iterator = dtPerpus.peminjamList.iterator();
        while (iterator.hasNext()) {
            Peminjam peminjam = iterator.next();
            if (peminjam.getId().equals(idPeminjam)) {
                return peminjam;
            }
        }
        return null;
    }    
    private void tampilKoleksi(){
        String IsbnIssn = "";
        String[] kolom = {"Id Koleksi","Judul","Penerbit","Status","ISBN/ISSN"};
        Object[][] objData = new Object[dtPesanKoleksi.size()][5]; // 5 merupakan jumlah kolom
        int i = 0;
        for(Koleksi n : dtPesanKoleksi){
            if (n instanceof Disk){
                IsbnIssn = ((Disk) n).getIsbn();
            }
            if (n instanceof majalah){
                IsbnIssn = ((majalah) n).getIssn();
            }
            if (n instanceof Buku){
                IsbnIssn = ((Buku) n).getIsbn();
            }
            objData[i] = new String[]{n.getId_Koleksi(), n.getJudul(), n.getPenerbit(), n.statuc_peminjam ? "Dipinjam" : "Tersedia", IsbnIssn};
            i++;
        }
        tbModelPesanKoleksi = new DefaultTableModel(objData,kolom){
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        TabelKoleksi.repaint();
        TabelKoleksi.setModel(tbModelPesanKoleksi);
        clModelPesanKoleksi = TabelKoleksi.getColumnModel();
        clModelPesanKoleksi.getColumn(0).setPreferredWidth(10);
        clModelPesanKoleksi.getColumn(1).setPreferredWidth(300);
        clModelPesanKoleksi.getColumn(2).setPreferredWidth(50);
        clModelPesanKoleksi.getColumn(3).setPreferredWidth(10);
        clModelPesanKoleksi.getColumn(4).setPreferredWidth(20);
    }
    private void tampilTransaksi(){
        String[] kolom = {"ID Transaksi","Tgl Pinjam","Tgl Kembali","ID Peminjam"};
        Object[][] objData = new Object[dtTrx.size()][4]; // 5 merupakan jumlah kolom
        int i = 0;
        for(Transaksi n : dtTrx){
            objData[i] = new String[]{n.getId_transaksi(), n.getTgl_peminjam().toString(), n.getTgl_kembali().toString(), n.getBorrow().getId()};
            i++;
        }
        tbModelTransaksi = new DefaultTableModel(objData,kolom){
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        DataTransaksi.repaint();
        DataTransaksi.setModel(tbModelTransaksi);
        clModelTransaksi = DataTransaksi.getColumnModel();
        clModelTransaksi.getColumn(0).setPreferredWidth(10);
        clModelTransaksi.getColumn(1).setPreferredWidth(300);
        clModelTransaksi.getColumn(2).setPreferredWidth(50);
        clModelTransaksi.getColumn(3).setPreferredWidth(10);
//        clModelTransaksi.getColumn(4).setPreferredWidth(20);
    }

    private void clrKoleksi(){
        tTambahPesan.setEnabled(Boolean.FALSE);
        txIDk.setText("");
        txJudul.setText("");
        txPenerbit.setText("");
        txStatus.setText("");
        txIssn.setText("");
        txVolume.setText("");
        txSeri.setText("");
    }   

    private void clrPeminjam(){
        txID.setText("");
        txNama.setText("");
        txAlamat.setText("");
        txJumPinjam.setText("");
        txNip.setText("");
    }
    
      public void kueri () throws SQLException {
          
          char tipe=txID.getText().charAt(0);
          
          switch (tipe) {
              case 'D' :
                  String query="SELECT * FROM DOSEN WHERE ID_DOSEN LIKE ?";
        PreparedStatement ps =connection.prepareStatement(query);
        ps.setString(1,txID.getText());
       ResultSet rs=ps.executeQuery();    //   JOptionPane.showMessageDialog(null, query);
      //  rs=stmt.executeQuery(query);
        if (rs.next()) { 
            //JOptionPane.showMessageDialog(null,rs.getString(1));
                txJumPinjam.setText(rs.getString(5));
               txAlamat.setText(rs.getString(4));
               txNama.setText(rs.getString(3));
               txNip.setText(rs.getString(2));
        }
              else { 
            JOptionPane.showMessageDialog(null,"Not Found");
        }
                  break;
                  
              case 'M' :
                  
                  String query2="SELECT * FROM MAHASISWA WHERE ID_MAHASISWA LIKE ?";
        PreparedStatement ps2 =connection.prepareStatement(query2);
        ps2.setString(1,txID.getText());
       ResultSet rs2=ps2.executeQuery();    //   JOptionPane.showMessageDialog(null, query);
      //  rs=stmt.executeQuery(query);
        if (rs2.next()) { 
            //JOptionPane.showMessageDialog(null,rs.getString(1));
                txJumPinjam.setText(rs2.getString(5));
               txAlamat.setText(rs2.getString(4));
               txNama.setText(rs2.getString(3));
               txNip.setText(rs2.getString(2));
        }
              else { 
            JOptionPane.showMessageDialog(null,"Not Found");
        } 
                  
                  
                  
                  
                  break;
                  
              case 'U' : 
                  
         String query3="SELECT * FROM UMUM WHERE ID_U LIKE ?";
        PreparedStatement ps3 =connection.prepareStatement(query3);
        ps3.setString(1,txID.getText());
       ResultSet rs3=ps3.executeQuery();    //   JOptionPane.showMessageDialog(null, query);
      //  rs=stmt.executeQuery(query);
        if (rs3.next()) { 
            //JOptionPane.showMessageDialog(null,rs.getString(1));
                txJumPinjam.setText(rs3.getString(5));
               txAlamat.setText(rs3.getString(4));
               txNama.setText(rs3.getString(3));
               txNip.setText(rs3.getString(2));
        }
              else { 
            JOptionPane.showMessageDialog(null,"Not Found");
        } 
                  
                  break;
          }
         
          
      }
      public void kueri_Koleksi () throws SQLException {
             
          char tipe=txIDk.getText().charAt(0);
          
          switch (tipe) {
              case 'B' :
                  String query="SELECT * FROM BOOK WHERE ID_B LIKE ?";
        PreparedStatement ps =connection.prepareStatement(query);
        ps.setString(1,txIDk.getText());
       ResultSet rs=ps.executeQuery();    //   JOptionPane.showMessageDialog(null, query);
      //  rs=stmt.executeQuery(query);
        if (rs.next()) { 
            //JOptionPane.showMessageDialog(null,rs.getString(1));
                txSeri.setVisible(Boolean.FALSE);
                lSeriK.setText(" ");
                txVolume.setText(rs.getString(4));
                lVolumeK.setText("Halaman");
                txIssn.setText(rs.getString(5));
           
               txPenerbit.setText(rs.getString(3));
               txJudul.setText(rs.getString(2));
        }
              else { 
            JOptionPane.showMessageDialog(null,"Not Found");
        }
                  break;
                  
              case 'M' :
                  
                  String query2="SELECT * FROM MAJALAH WHERE ID_M LIKE ?";
        PreparedStatement ps2 =connection.prepareStatement(query2);
        ps2.setString(1,txIDk.getText());
       ResultSet rs2=ps2.executeQuery();    //   JOptionPane.showMessageDialog(null, query);
      //  rs=stmt.executeQuery(query);
        if (rs2.next()) { 
            //JOptionPane.showMessageDialog(null,rs.getString(1));
                 lVolumeK.setText("Volume");
                lSeriK.setText("Seri");
                txSeri.setVisible(Boolean.TRUE);
                txSeri.setText(rs2.getString(5));
                txVolume.setText(rs2.getString(4));
                    txIssn.setText(rs2.getString(6));
               
               txPenerbit.setText(rs2.getString(3));
               txJudul.setText(rs2.getString(2));
        }
              else { 
            JOptionPane.showMessageDialog(null,"Not Found");
        } 
                  
                  
                            
                 break;
                  
              case 'D' : 
                  
                  String query3="SELECT * FROM CD WHERE ID_D LIKE ?";
        PreparedStatement ps3 =connection.prepareStatement(query3);
        ps3.setString(1,txIDk.getText());
       ResultSet rs3=ps3.executeQuery();    //   JOptionPane.showMessageDialog(null, query);
      //  rs=stmt.executeQuery(query);
        if (rs3.next()) { 
            //JOptionPane.showMessageDialog(null,rs.getString(1));
                lVolumeK.setText("Format");
                lSeriK.setText("   ");
                txSeri.setVisible(Boolean.FALSE);
                txVolume.setText(rs3.getString(4));
                    txIssn.setText(rs3.getString(5));
              
               txPenerbit.setText(rs3.getString(3));
               txJudul.setText(rs3.getString(2));
        }
              else { 
            JOptionPane.showMessageDialog(null,"Not Found");
        } 
                  
                  break;
          }
         
      }
      public void Connection() throws SQLException{
           try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            connection = DriverManager.getConnection(jdbcURL, user, password);
            JOptionPane.showMessageDialog(null,"Success");
            stmt=connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
        } catch (Exception ex) {
            System.out.println("message: " + ex.getMessage());
        }
      }

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buka;
    private javax.swing.JTable DataTransaksi;
    private javax.swing.JButton Detil;
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Simpan;
    private javax.swing.JTable TabelKoleksi;
    private javax.swing.JButton btPinjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lSeriK;
    private javax.swing.JLabel lVolumeK;
    private javax.swing.JLabel lblNo;
    private javax.swing.JLabel lblNo1;
    private javax.swing.JButton tBatal;
    private javax.swing.JButton tBatalK;
    private javax.swing.JButton tCari;
    private javax.swing.JButton tCaruKoleksi;
    private javax.swing.JButton tTambahPesan;
    private javax.swing.JTextField txAlamat;
    private javax.swing.JTextField txID;
    private javax.swing.JTextField txIDk;
    private javax.swing.JTextField txIssn;
    private javax.swing.JTextField txJudul;
    private javax.swing.JTextField txJumPinjam;
    private javax.swing.JTextField txNama;
    private javax.swing.JTextField txNip;
    private javax.swing.JTextField txPenerbit;
    private javax.swing.JTextField txSeri;
    private javax.swing.JTextField txStatus;
    private javax.swing.JTextField txVolume;
    // End of variables declaration//GEN-END:variables
}
